-- Usage tracking table for adoption metrics.
-- Run once against HANA Cloud to create the table and indexes.

CREATE COLUMN TABLE SVA2.USAGE_LOG (
    ID            NVARCHAR(36)   PRIMARY KEY,
    TS            TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    CLIENT_IP     NVARCHAR(45),
    TOOL_NAME     NVARCHAR(50)   NOT NULL,
    SOLUTION      NVARCHAR(100),
    PAIN_POINT_SUMMARY NVARCHAR(200),
    RESULTS_COUNT INTEGER,
    TOP_SIMILARITY DECIMAL(5,4),
    RESPONSE_TIME_MS INTEGER,
    SUCCESS       BOOLEAN        DEFAULT TRUE
);

CREATE INDEX IDX_USAGE_TS   ON SVA2.USAGE_LOG(TS);
CREATE INDEX IDX_USAGE_IP   ON SVA2.USAGE_LOG(CLIENT_IP);
CREATE INDEX IDX_USAGE_TOOL ON SVA2.USAGE_LOG(TOOL_NAME);
