-- ============================================================
-- SVA2 HANA Cloud Schema
-- Last updated: 2026-05-26
-- ============================================================

-- Schema
CREATE SCHEMA SVA2;

-- Main vector table
CREATE COLUMN TABLE SVA2.PAIN_POINTS (
    ID              VARCHAR(36) DEFAULT SYSUUID PRIMARY KEY,  -- UUID
    SOURCE_FILE     NVARCHAR(255),

    -- Embeddable field (text used for vector generation)
    -- Only pain_point is embedded to maximize similarity precision
    PAIN_POINT      NVARCHAR(2000) NOT NULL,

    -- Metadata filters (used in WHERE clause before vector search)
    SOLUTION        NVARCHAR(100),   -- e.g. Ariba Sourcing, Ariba Buying, etc.
    SOLUTION_AREA   NVARCHAR(100),   -- e.g. Integration, Supplier Management, etc.
    CATEGORY        NVARCHAR(50),    -- Feature Adoption | Innovation | Training | Process Change
                                     -- Q&A and Roadmap Discussion are NOT indexed

    -- Payload fields (returned at retrieval time as RAG context for LLM)
    RECOMMENDATION  NVARCHAR(4000),  -- Generated by LLM or from historical case
    EFFORT          NVARCHAR(20),    -- Low | Medium | High | Complex | N/A
    TIMELINE        NVARCHAR(20),    -- Quick Win | Short Term | Mid Term | Long Term
    BENEFITS        NVARCHAR(2000),  -- Generated by LLM using full case context

    -- Specialist-only fields (not used by LLM, filled after generation)
    IMPACT          NVARCHAR(20),    -- High | Medium | Low | N/A — filled by specialist

    -- Provenance metadata
    SOURCE_TYPE     NVARCHAR(30),    -- historical_excel | joule_approved | joule_edited
    APPROVED_BY     NVARCHAR(100),   -- consultant ID (for feedback loop cases)
    APPROVED_AT     TIMESTAMP,       -- when the case was approved

    -- Quality tracking (computed over time)
    USE_COUNT       INTEGER DEFAULT 0,   -- times retrieved and used in a generation
    QUALITY_SCORE   DECIMAL(3,2),        -- computed quality score over time

    -- Timestamp
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Vector column — 3072 dims for text-embedding-3-large
    EMBEDDING       REAL_VECTOR(3072)
);

-- Indexes for fast metadata filtering before vector search
CREATE INDEX IDX_SOLUTION      ON SVA2.PAIN_POINTS (SOLUTION);
CREATE INDEX IDX_SOLUTION_AREA ON SVA2.PAIN_POINTS (SOLUTION_AREA);
CREATE INDEX IDX_CATEGORY      ON SVA2.PAIN_POINTS (CATEGORY);
CREATE INDEX IDX_SOURCE_TYPE   ON SVA2.PAIN_POINTS (SOURCE_TYPE);